### PR TITLE
adapted to configurable paths

### PR DESCRIPTION
**Pull request by makuhama**
see https://github.com/getgrav/grav/issues/3297

### CODE REVIEW

**Review by mahagr — APPROVED** [review]

**Comment by mahagr** [comment]
@rhukster These changes are needed to make problems plugin to work with custom paths.

**Comment by mahagr** [comment]
I'm starting to wonder if the plugin should use those at all... As at the point when the plugin runs, all of those paths may have been changed by the configuration.

**Comment by makuhama** [comment]
> I'm starting to wonder if the plugin should use those at all... As at the point when the plugin runs, all of those paths may have been changed by the configuration.

Actually that's a good point from my packager perspective. Nevertheless I would prefer to have this patch in the main branch. Sooner or later (probably after configurable paths have been documented) someone will install Grav manually and take advantage of configurable paths (as I did initially) and run into the problems plugin complaining about missing or non-writeable directories.

**Comment by mahagr** [comment]
I just updated the plugin to support this better as well as went through the code.

**Pull request closed without merging**
